export const topics = [
  {
    id: "programming",
    name: "Programming",
    icon: "</>",
    description: "Code, logic & the web",
  },
  {
    id: "science",
    name: "Science",
    icon: "✳",
    description: "Discover how things work",
  },
  {
    id: "general",
    name: "General Knowledge",
    icon: "◎",
    description: "A little bit of everything",
  },
  {
    id: "history",
    name: "History",
    icon: "⌛",
    description: "People, events & civilizations",
  },
  {
    id: "geography",
    name: "Geography",
    icon: "⌖",
    description: "Countries, maps & the world",
  },
];

export const questions = [
  // =====================================================
  // PROGRAMMING — EASY (8)
  // =====================================================
  {
    id: "p-e-01",
    topic: "programming",
    subtopic: "HTML",
    difficulty: "easy",
    question: "Which HTML element creates a hyperlink?",
    options: ["<link>", "<a>", "<href>", "<nav>"],
    correctAnswer: "<a>",
    explanation: "The <a> element creates a hyperlink.",
  },
  {
    id: "p-e-02",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "easy",
    question: "Which keyword declares a block-scoped variable that can be reassigned?",
    options: ["const", "let", "define", "static"],
    correctAnswer: "let",
    explanation: "let declares a block-scoped variable that can be reassigned.",
  },
  {
    id: "p-e-03",
    topic: "programming",
    subtopic: "CSS",
    difficulty: "easy",
    question: "Which CSS property changes text colour?",
    options: ["font-style", "background", "color", "text-size"],
    correctAnswer: "color",
    explanation: "The color property changes the colour of text.",
  },
  {
    id: "p-e-04",
    topic: "programming",
    subtopic: "HTML",
    difficulty: "easy",
    question: "Which HTML tag displays an image?",
    options: ["<image>", "<img>", "<picture-src>", "<media>"],
    correctAnswer: "<img>",
    explanation: "The img element embeds an image in a webpage.",
  },
  {
    id: "p-e-05",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "easy",
    question: "Which symbol begins a single-line JavaScript comment?",
    options: ["<!--", "//", "**", "##"],
    correctAnswer: "//",
    explanation: "JavaScript uses // for single-line comments.",
  },
  {
    id: "p-e-06",
    topic: "programming",
    subtopic: "CSS",
    difficulty: "easy",
    question: "Which selector targets an element with id=\"main\"?",
    options: [".main", "#main", "main()", "*main"],
    correctAnswer: "#main",
    explanation: "The # selector targets an element by its ID.",
  },
  {
    id: "p-e-07",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "easy",
    question: "Which value represents a Boolean true value in JavaScript?",
    options: ["\"true\"", "1", "true", "\"yes\""],
    correctAnswer: "true",
    explanation: "true is a Boolean value; \"true\" is a string.",
  },
  {
    id: "p-e-08",
    topic: "programming",
    subtopic: "HTML",
    difficulty: "easy",
    question: "Which HTML element is used for the largest heading by default?",
    options: ["<h6>", "<head>", "<h1>", "<heading>"],
    correctAnswer: "<h1>",
    explanation: "The h1 element represents the highest-level heading.",
  },

  // =====================================================
  // PROGRAMMING — MEDIUM (8)
  // =====================================================
  {
    id: "p-m-01",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "medium",
    question: "What does Array.prototype.filter() return?",
    options: [
      "The first matching element",
      "A new array of matching elements",
      "A number of matching elements",
      "The original array, always modified",
    ],
    correctAnswer: "A new array of matching elements",
    explanation: "filter() returns a new array containing elements that pass its test.",
  },
  {
    id: "p-m-02",
    topic: "programming",
    subtopic: "CSS",
    difficulty: "medium",
    question: "Which CSS declaration enables a two-dimensional grid layout?",
    options: [
      "display: block",
      "position: relative",
      "display: grid",
      "float: grid",
    ],
    correctAnswer: "display: grid",
    explanation: "CSS Grid supports layouts using rows and columns.",
  },
  {
    id: "p-m-03",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "medium",
    question: "Which array method adds an item to the end of an array?",
    options: ["push()", "pop()", "shift()", "slice()"],
    correctAnswer: "push()",
    explanation: "push() appends one or more items to an array.",
  },
  {
    id: "p-m-04",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "medium",
    question: "What does the === operator compare?",
    options: [
      "Only the value",
      "Only the type",
      "Value and type",
      "Variable names",
    ],
    correctAnswer: "Value and type",
    explanation: "Strict equality compares values without type coercion.",
  },
  {
    id: "p-m-05",
    topic: "programming",
    subtopic: "HTML",
    difficulty: "medium",
    question: "What is the purpose of an image's alt attribute?",
    options: [
      "Resize the image",
      "Provide alternative text",
      "Add a border",
      "Play a video",
    ],
    correctAnswer: "Provide alternative text",
    explanation: "Alternative text improves accessibility and describes the image.",
  },
  {
    id: "p-m-06",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "medium",
    question: "Which array method transforms each item into a new array item?",
    options: ["map()", "find()", "includes()", "join()"],
    correctAnswer: "map()",
    explanation: "map() applies a callback to each element and returns a new array.",
  },
  {
    id: "p-m-07",
    topic: "programming",
    subtopic: "Web",
    difficulty: "medium",
    question: "What does an HTTP 404 status usually mean?",
    options: [
      "Request successful",
      "Unauthorized",
      "Resource not found",
      "Server started",
    ],
    correctAnswer: "Resource not found",
    explanation: "A 404 response means the requested resource could not be found.",
  },
  {
    id: "p-m-08",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "medium",
    question: "Which method converts a JSON string into a JavaScript value?",
    options: [
      "JSON.stringify()",
      "JSON.parse()",
      "JSON.convert()",
      "JSON.read()",
    ],
    correctAnswer: "JSON.parse()",
    explanation: "JSON.parse() parses a JSON-formatted string.",
  },

  // =====================================================
  // PROGRAMMING — HARD (8)
  // =====================================================
  {
    id: "p-h-01",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "hard",
    question: "What does this code throw?\n\nlet x = 1;\nfunction test() {\n  console.log(x);\n  let x = 2;\n}\ntest();",
    options: ["1", "2", "undefined", "ReferenceError"],
    correctAnswer: "ReferenceError",
    explanation: "The local x is in its temporal dead zone before its let declaration.",
  },
  {
    id: "p-h-02",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "hard",
    question: "What happens when Promise.all() receives a rejected promise?",
    options: [
      "It ignores the rejection",
      "The combined promise rejects",
      "It retries automatically",
      "It converts the rejection to null",
    ],
    correctAnswer: "The combined promise rejects",
    explanation: "Promise.all() rejects when an input promise rejects.",
  },
  {
    id: "p-h-03",
    topic: "programming",
    subtopic: "Algorithms",
    difficulty: "hard",
    question: "What is binary search's time complexity on a sorted array?",
    options: ["O(n)", "O(n²)", "O(log n)", "O(1) always"],
    correctAnswer: "O(log n)",
    explanation: "Binary search halves the remaining search range at each step.",
  },
  {
    id: "p-h-04",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "hard",
    question: "What does a closure retain access to?",
    options: [
      "Only global variables",
      "Its surrounding lexical environment",
      "Only function parameters",
      "Browser history",
    ],
    correctAnswer: "Its surrounding lexical environment",
    explanation: "A closure can access variables from its lexical scope.",
  },
  {
    id: "p-h-05",
    topic: "programming",
    subtopic: "Web",
    difficulty: "hard",
    question: "What is the main purpose of CORS?",
    options: [
      "Compress files",
      "Control cross-origin browser access",
      "Encrypt passwords",
      "Style webpages",
    ],
    correctAnswer: "Control cross-origin browser access",
    explanation: "CORS lets servers specify which origins can access resources through browsers.",
  },
  {
    id: "p-h-06",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "hard",
    question: "What does declaring an object with const prevent?",
    options: [
      "Changing any property",
      "Reassigning the variable",
      "Reading its properties",
      "Passing it to a function",
    ],
    correctAnswer: "Reassigning the variable",
    explanation: "const prevents rebinding the variable, but object properties may still change.",
  },
  {
    id: "p-h-07",
    topic: "programming",
    subtopic: "Web",
    difficulty: "hard",
    question: "Which HTTP method is commonly used to retrieve a resource?",
    options: ["POST", "PATCH", "GET", "DELETE"],
    correctAnswer: "GET",
    explanation: "GET requests a representation of a resource.",
  },
  {
    id: "p-h-08",
    topic: "programming",
    subtopic: "JavaScript",
    difficulty: "hard",
    question: "What does the await keyword do inside an async function?",
    options: [
      "Stops the whole browser",
      "Waits for a promise to settle before continuing that function",
      "Makes every function synchronous",
      "Deletes a promise",
    ],
    correctAnswer: "Waits for a promise to settle before continuing that function",
    explanation: "await pauses the async function until the promise settles, without blocking the main thread.",
  },

  // =====================================================
  // SCIENCE — EASY (8)
  // =====================================================
  {
    id: "s-e-01",
    topic: "science",
    subtopic: "Astronomy",
    difficulty: "easy",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    correctAnswer: "Mars",
    explanation: "Iron-rich dust gives Mars its reddish appearance.",
  },
  {
    id: "s-e-02",
    topic: "science",
    subtopic: "Biology",
    difficulty: "easy",
    question: "Which organ pumps blood around the human body?",
    options: ["Liver", "Lung", "Heart", "Kidney"],
    correctAnswer: "Heart",
    explanation: "The heart pumps blood through the circulatory system.",
  },
  {
    id: "s-e-03",
    topic: "science",
    subtopic: "Chemistry",
    difficulty: "easy",
    question: "What is the chemical formula for water?",
    options: ["CO2", "O2", "H2O", "NaCl"],
    correctAnswer: "H2O",
    explanation: "A water molecule contains two hydrogen atoms and one oxygen atom.",
  },
  {
    id: "s-e-04",
    topic: "science",
    subtopic: "Physics",
    difficulty: "easy",
    question: "What force pulls objects toward Earth?",
    options: ["Magnetism", "Gravity", "Friction", "Electricity"],
    correctAnswer: "Gravity",
    explanation: "Gravity attracts objects with mass toward one another.",
  },
  {
    id: "s-e-05",
    topic: "science",
    subtopic: "Biology",
    difficulty: "easy",
    question: "Which gas do humans need for aerobic respiration?",
    options: ["Carbon dioxide", "Helium", "Oxygen", "Hydrogen"],
    correctAnswer: "Oxygen",
    explanation: "Cells use oxygen during aerobic respiration.",
  },
  {
    id: "s-e-06",
    topic: "science",
    subtopic: "Astronomy",
    difficulty: "easy",
    question: "Which star is closest to Earth?",
    options: ["Sirius", "The Sun", "Polaris", "Vega"],
    correctAnswer: "The Sun",
    explanation: "The Sun is Earth's nearest star.",
  },
  {
    id: "s-e-07",
    topic: "science",
    subtopic: "Biology",
    difficulty: "easy",
    question: "Which plant part usually absorbs water from the soil?",
    options: ["Flower", "Roots", "Fruit", "Petal"],
    correctAnswer: "Roots",
    explanation: "Roots absorb water and minerals from the soil.",
  },
  {
    id: "s-e-08",
    topic: "science",
    subtopic: "Physics",
    difficulty: "easy",
    question: "At standard pressure, at what temperature does water freeze?",
    options: ["0°C", "10°C", "50°C", "100°C"],
    correctAnswer: "0°C",
    explanation: "Pure water freezes at 0°C under standard atmospheric pressure.",
  },

  // =====================================================
  // SCIENCE — MEDIUM (8)
  // =====================================================
  {
    id: "s-m-01",
    topic: "science",
    subtopic: "Physics",
    difficulty: "medium",
    question: "What is the SI unit of electric current?",
    options: ["Volt", "Ohm", "Watt", "Ampere"],
    correctAnswer: "Ampere",
    explanation: "The ampere is the SI base unit for electric current.",
  },
  {
    id: "s-m-02",
    topic: "science",
    subtopic: "Chemistry",
    difficulty: "medium",
    question: "What is the approximate pH of pure water at 25°C?",
    options: ["3", "5", "7", "10"],
    correctAnswer: "7",
    explanation: "Pure water is neutral at approximately pH 7 at 25°C.",
  },
  {
    id: "s-m-03",
    topic: "science",
    subtopic: "Biology",
    difficulty: "medium",
    question: "Which cell structure contains most human-cell DNA?",
    options: ["Ribosome", "Nucleus", "Cell wall", "Golgi apparatus"],
    correctAnswer: "Nucleus",
    explanation: "Most DNA in a human cell is located in the nucleus.",
  },
  {
    id: "s-m-04",
    topic: "science",
    subtopic: "Physics",
    difficulty: "medium",
    question: "Which unit measures force?",
    options: ["Joule", "Watt", "Newton", "Pascal"],
    correctAnswer: "Newton",
    explanation: "The newton is the SI unit of force.",
  },
  {
    id: "s-m-05",
    topic: "science",
    subtopic: "Chemistry",
    difficulty: "medium",
    question: "What is the atomic number of carbon?",
    options: ["4", "6", "8", "12"],
    correctAnswer: "6",
    explanation: "Carbon has six protons, so its atomic number is 6.",
  },
  {
    id: "s-m-06",
    topic: "science",
    subtopic: "Astronomy",
    difficulty: "medium",
    question: "What is the main cause of Earth's seasons?",
    options: [
      "Earth's distance from the Sun alone",
      "Earth's axial tilt",
      "The Moon's shadow",
      "Solar flares",
    ],
    correctAnswer: "Earth's axial tilt",
    explanation: "Earth's tilted axis changes the angle and duration of sunlight throughout the year.",
  },
  {
    id: "s-m-07",
    topic: "science",
    subtopic: "Biology",
    difficulty: "medium",
    question: "Which blood cells help defend the body against infection?",
    options: [
      "Red blood cells",
      "White blood cells",
      "Platelets only",
      "Plasma only",
    ],
    correctAnswer: "White blood cells",
    explanation: "White blood cells are key components of the immune system.",
  },
  {
    id: "s-m-08",
    topic: "science",
    subtopic: "Chemistry",
    difficulty: "medium",
    question: "What is the main gas in Earth's atmosphere?",
    options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
    correctAnswer: "Nitrogen",
    explanation: "Nitrogen makes up about 78% of dry air.",
  },

  // =====================================================
  // SCIENCE — HARD (8)
  // =====================================================
  {
    id: "s-h-01",
    topic: "science",
    subtopic: "Physics",
    difficulty: "hard",
    question: "Ignoring air resistance, what happens to a projectile's horizontal velocity?",
    options: [
      "It increases continuously",
      "It decreases continuously",
      "It remains constant",
      "It becomes zero at the highest point",
    ],
    correctAnswer: "It remains constant",
    explanation: "Gravity acts vertically, so horizontal acceleration is zero in ideal projectile motion.",
  },
  {
    id: "s-h-02",
    topic: "science",
    subtopic: "Biology",
    difficulty: "hard",
    question: "Which process produces most ATP during aerobic respiration?",
    options: [
      "Glycolysis",
      "Fermentation",
      "Oxidative phosphorylation",
      "DNA replication",
    ],
    correctAnswer: "Oxidative phosphorylation",
    explanation: "The electron transport chain and ATP synthase generate most ATP during aerobic respiration.",
  },
  {
    id: "s-h-03",
    topic: "science",
    subtopic: "Physics",
    difficulty: "hard",
    question: "Which equation relates wave speed, frequency and wavelength?",
    options: ["v = fλ", "F = ma²", "P = IV²", "E = mc"],
    correctAnswer: "v = fλ",
    explanation: "Wave speed equals frequency multiplied by wavelength.",
  },
  {
    id: "s-h-04",
    topic: "science",
    subtopic: "Biology",
    difficulty: "hard",
    question: "Which enzyme unwinds DNA during replication?",
    options: ["Amylase", "Helicase", "Lipase", "Lactase"],
    correctAnswer: "Helicase",
    explanation: "Helicase separates the DNA strands during replication.",
  },
  {
    id: "s-h-05",
    topic: "science",
    subtopic: "Chemistry",
    difficulty: "hard",
    question: "What is oxygen's oxidation state in most compounds?",
    options: ["+1", "-1", "-2", "+2"],
    correctAnswer: "-2",
    explanation: "Oxygen usually has an oxidation state of -2, with some exceptions.",
  },
  {
    id: "s-h-06",
    topic: "science",
    subtopic: "Astronomy",
    difficulty: "hard",
    question: "What is the boundary around a black hole beyond which light cannot escape?",
    options: [
      "Photosphere",
      "Event horizon",
      "Asteroid belt",
      "Chromosphere",
    ],
    correctAnswer: "Event horizon",
    explanation: "The event horizon marks the boundary beyond which escape is impossible.",
  },
  {
    id: "s-h-07",
    topic: "science",
    subtopic: "Physics",
    difficulty: "hard",
    question: "Which law states that entropy in an isolated system tends not to decrease?",
    options: [
      "First law of motion",
      "Second law of thermodynamics",
      "Ohm's law",
      "Hooke's law",
    ],
    correctAnswer: "Second law of thermodynamics",
    explanation: "The second law describes the tendency of total entropy to increase.",
  },
  {
    id: "s-h-08",
    topic: "science",
    subtopic: "Biology",
    difficulty: "hard",
    question: "Where does the Calvin cycle take place in plant cells?",
    options: [
      "Thylakoid lumen",
      "Chloroplast stroma",
      "Mitochondrial matrix",
      "Nucleus",
    ],
    correctAnswer: "Chloroplast stroma",
    explanation: "The Calvin cycle takes place in the stroma of the chloroplast.",
  },

  // =====================================================
  // GENERAL KNOWLEDGE — EASY (8)
  // =====================================================
  {
    id: "g-e-01",
    topic: "general",
    subtopic: "Geography",
    difficulty: "easy",
    question: "What is the capital of Japan?",
    options: ["Kyoto", "Tokyo", "Osaka", "Nagoya"],
    correctAnswer: "Tokyo",
    explanation: "Tokyo is Japan's capital.",
  },
  {
    id: "g-e-02",
    topic: "general",
    subtopic: "Geography",
    difficulty: "easy",
    question: "Which is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswer: "Pacific Ocean",
    explanation: "The Pacific is Earth's largest ocean.",
  },
  {
    id: "g-e-03",
    topic: "general",
    subtopic: "Literature",
    difficulty: "easy",
    question: "Who wrote the Harry Potter book series?",
    options: [
      "J. K. Rowling",
      "Jane Austen",
      "Mark Twain",
      "Roald Dahl",
    ],
    correctAnswer: "J. K. Rowling",
    explanation: "J. K. Rowling wrote the Harry Potter series.",
  },
  {
    id: "g-e-04",
    topic: "general",
    subtopic: "Sports",
    difficulty: "easy",
    question: "How many players from one football team are normally on the field?",
    options: ["7", "9", "11", "13"],
    correctAnswer: "11",
    explanation: "Association football teams normally field eleven players, including the goalkeeper.",
  },
  {
    id: "g-e-05",
    topic: "general",
    subtopic: "Music",
    difficulty: "easy",
    question: "Which instrument has black and white keys?",
    options: ["Flute", "Piano", "Trumpet", "Drum"],
    correctAnswer: "Piano",
    explanation: "A standard piano keyboard has black and white keys.",
  },
  {
    id: "g-e-06",
    topic: "general",
    subtopic: "Language",
    difficulty: "easy",
    question: "How many letters are there in the English alphabet?",
    options: ["24", "25", "26", "28"],
    correctAnswer: "26",
    explanation: "The modern English alphabet contains 26 letters.",
  },
  {
    id: "g-e-07",
    topic: "general",
    subtopic: "Inventions",
    difficulty: "easy",
    question: "Who is commonly credited with inventing the practical telephone?",
    options: [
      "Alexander Graham Bell",
      "Isaac Newton",
      "Nikola Tesla",
      "James Watt",
    ],
    correctAnswer: "Alexander Graham Bell",
    explanation: "Bell is commonly credited with developing the practical telephone.",
  },
  {
    id: "g-e-08",
    topic: "general",
    subtopic: "Food",
    difficulty: "easy",
    question: "Which fruit appears in the saying 'An ___ a day keeps the doctor away'?",
    options: ["Apple", "Grape", "Mango", "Pear"],
    correctAnswer: "Apple",
    explanation: "The traditional saying refers to an apple.",
  },

  // =====================================================
  // GENERAL KNOWLEDGE — MEDIUM (8)
  // =====================================================
  {
    id: "g-m-01",
    topic: "general",
    subtopic: "Geography",
    difficulty: "medium",
    question: "Which of these countries is crossed by the Equator?",
    options: ["Egypt", "Kenya", "Morocco", "South Africa"],
    correctAnswer: "Kenya",
    explanation: "The Equator crosses Kenya in East Africa.",
  },
  {
    id: "g-m-02",
    topic: "general",
    subtopic: "Literature",
    difficulty: "medium",
    question: "Who wrote the novel 1984?",
    options: [
      "Aldous Huxley",
      "George Orwell",
      "J. R. R. Tolkien",
      "H. G. Wells",
    ],
    correctAnswer: "George Orwell",
    explanation: "George Orwell published Nineteen Eighty-Four in 1949.",
  },
  {
    id: "g-m-03",
    topic: "general",
    subtopic: "Music",
    difficulty: "medium",
    question: "Which composer wrote The Four Seasons?",
    options: ["Mozart", "Vivaldi", "Chopin", "Beethoven"],
    correctAnswer: "Vivaldi",
    explanation: "Antonio Vivaldi composed The Four Seasons.",
  },
  {
    id: "g-m-04",
    topic: "general",
    subtopic: "Sports",
    difficulty: "medium",
    question: "In tennis, what term means a score of zero?",
    options: ["Love", "Nilby", "Blank", "Duck"],
    correctAnswer: "Love",
    explanation: "In tennis scoring, zero is called love.",
  },
  {
    id: "g-m-05",
    topic: "general",
    subtopic: "Literature",
    difficulty: "medium",
    question: "Who wrote Pride and Prejudice?",
    options: [
      "Emily Brontë",
      "Jane Austen",
      "Mary Shelley",
      "Virginia Woolf",
    ],
    correctAnswer: "Jane Austen",
    explanation: "Jane Austen published Pride and Prejudice in 1813.",
  },
  {
    id: "g-m-06",
    topic: "general",
    subtopic: "Art",
    difficulty: "medium",
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Michelangelo", "Raphael", "Van Gogh", "Monet"],
    correctAnswer: "Michelangelo",
    explanation: "Michelangelo painted the famous Sistine Chapel ceiling frescoes.",
  },
  {
    id: "g-m-07",
    topic: "general",
    subtopic: "Organizations",
    difficulty: "medium",
    question: "Where is the headquarters of the United Nations?",
    options: ["Geneva", "Paris", "New York City", "Vienna"],
    correctAnswer: "New York City",
    explanation: "The UN's principal headquarters is in New York City.",
  },
  {
    id: "g-m-08",
    topic: "general",
    subtopic: "Science",
    difficulty: "medium",
    question: "Who is associated with the discovery of penicillin?",
    options: [
      "Louis Pasteur",
      "Alexander Fleming",
      "Gregor Mendel",
      "Robert Hooke",
    ],
    correctAnswer: "Alexander Fleming",
    explanation: "Fleming observed penicillin's antibacterial effect in 1928.",
  },

  // =====================================================
  // GENERAL KNOWLEDGE — HARD (8)
  // =====================================================
  {
    id: "g-h-01",
    topic: "general",
    subtopic: "Astronomy",
    difficulty: "hard",
    question: "Which mission first landed humans on the Moon?",
    options: ["Apollo 8", "Apollo 10", "Apollo 11", "Gemini 8"],
    correctAnswer: "Apollo 11",
    explanation: "Apollo 11 achieved the first crewed lunar landing in July 1969.",
  },
  {
    id: "g-h-02",
    topic: "general",
    subtopic: "Geography",
    difficulty: "hard",
    question: "Which of these countries is landlocked?",
    options: ["Vietnam", "Cambodia", "Laos", "Thailand"],
    correctAnswer: "Laos",
    explanation: "Laos has no coastline and is bordered by five countries.",
  },
  {
    id: "g-h-03",
    topic: "general",
    subtopic: "Literature",
    difficulty: "hard",
    question: "Who wrote One Hundred Years of Solitude?",
    options: [
      "Gabriel García Márquez",
      "Jorge Luis Borges",
      "Pablo Neruda",
      "Mario Vargas Llosa",
    ],
    correctAnswer: "Gabriel García Márquez",
    explanation: "The novel was written by Colombian author Gabriel García Márquez.",
  },
  {
    id: "g-h-04",
    topic: "general",
    subtopic: "Economics",
    difficulty: "hard",
    question: "What does GDP stand for?",
    options: [
      "Gross Domestic Product",
      "General Development Plan",
      "Global Debt Percentage",
      "Gross Distribution Price",
    ],
    correctAnswer: "Gross Domestic Product",
    explanation: "GDP measures the value of final goods and services produced within an economy.",
  },
  {
    id: "g-h-05",
    topic: "general",
    subtopic: "Music",
    difficulty: "hard",
    question: "Which composer wrote the opera The Magic Flute?",
    options: ["Verdi", "Mozart", "Wagner", "Puccini"],
    correctAnswer: "Mozart",
    explanation: "Wolfgang Amadeus Mozart composed The Magic Flute.",
  },
  {
    id: "g-h-06",
    topic: "general",
    subtopic: "Philosophy",
    difficulty: "hard",
    question: "Who wrote The Republic?",
    options: ["Aristotle", "Plato", "Socrates", "Epicurus"],
    correctAnswer: "Plato",
    explanation: "Plato's Republic discusses justice and the ideal state.",
  },
  {
    id: "g-h-07",
    topic: "general",
    subtopic: "Organizations",
    difficulty: "hard",
    question: "Which city hosts the International Court of Justice?",
    options: ["The Hague", "Brussels", "Rome", "Strasbourg"],
    correctAnswer: "The Hague",
    explanation: "The International Court of Justice is based in The Hague, Netherlands.",
  },
  {
    id: "g-h-08",
    topic: "general",
    subtopic: "Awards",
    difficulty: "hard",
    question: "Which Nobel Prize category was not part of Alfred Nobel's original will?",
    options: ["Physics", "Chemistry", "Literature", "Economic Sciences"],
    correctAnswer: "Economic Sciences",
    explanation: "The economics prize was established later, in 1968.",
  },

  // =====================================================
  // HISTORY — EASY (8)
  // =====================================================
  {
    id: "h-e-01",
    topic: "history",
    subtopic: "Ancient History",
    difficulty: "easy",
    question: "Which ancient civilization built the pyramids at Giza?",
    options: ["Romans", "Ancient Egyptians", "Vikings", "Persians"],
    correctAnswer: "Ancient Egyptians",
    explanation: "The pyramids at Giza were built in ancient Egypt during the Old Kingdom.",
  },
  {
    id: "h-e-02",
    topic: "history",
    subtopic: "World History",
    difficulty: "easy",
    question: "The Great Wall is most closely associated with which country?",
    options: ["India", "China", "Greece", "Mexico"],
    correctAnswer: "China",
    explanation: "The Great Wall is a network of fortifications across northern China.",
  },
  {
    id: "h-e-03",
    topic: "history",
    subtopic: "World History",
    difficulty: "easy",
    question: "Which ship carried the Pilgrims to North America in 1620?",
    options: ["Mayflower", "Endeavour", "Santa Maria", "Beagle"],
    correctAnswer: "Mayflower",
    explanation: "The Mayflower carried the Pilgrims to North America.",
  },
  {
    id: "h-e-04",
    topic: "history",
    subtopic: "Ancient History",
    difficulty: "easy",
    question: "Which city was buried by the eruption of Mount Vesuvius in AD 79?",
    options: ["Athens", "Pompeii", "Sparta", "Carthage"],
    correctAnswer: "Pompeii",
    explanation: "Pompeii was buried by volcanic material from Mount Vesuvius.",
  },
  {
    id: "h-e-05",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "easy",
    question: "Who was the first Prime Minister of independent India?",
    options: [
      "Mahatma Gandhi",
      "Jawaharlal Nehru",
      "Sardar Patel",
      "Rajendra Prasad",
    ],
    correctAnswer: "Jawaharlal Nehru",
    explanation: "Jawaharlal Nehru became India's first prime minister in 1947.",
  },
  {
    id: "h-e-06",
    topic: "history",
    subtopic: "Ancient History",
    difficulty: "easy",
    question: "Which ancient people developed democracy in Athens?",
    options: ["Ancient Greeks", "Romans", "Sumerians", "Phoenicians"],
    correctAnswer: "Ancient Greeks",
    explanation: "A form of direct democracy developed in ancient Athens.",
  },
  {
    id: "h-e-07",
    topic: "history",
    subtopic: "World History",
    difficulty: "easy",
    question: "In which year did the Titanic sink?",
    options: ["1905", "1912", "1920", "1931"],
    correctAnswer: "1912",
    explanation: "The Titanic sank in April 1912 during its maiden voyage.",
  },
  {
    id: "h-e-08",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "easy",
    question: "Which monument was commissioned by Shah Jahan in memory of Mumtaz Mahal?",
    options: ["Red Fort", "Taj Mahal", "Qutub Minar", "India Gate"],
    correctAnswer: "Taj Mahal",
    explanation: "Shah Jahan commissioned the Taj Mahal as a mausoleum for Mumtaz Mahal.",
  },

  // =====================================================
  // HISTORY — MEDIUM (8)
  // =====================================================
  {
    id: "h-m-01",
    topic: "history",
    subtopic: "Modern History",
    difficulty: "medium",
    question: "In which year did World War II end?",
    options: ["1918", "1939", "1945", "1963"],
    correctAnswer: "1945",
    explanation: "World War II ended in 1945.",
  },
  {
    id: "h-m-02",
    topic: "history",
    subtopic: "European History",
    difficulty: "medium",
    question: "Which city was divided by a wall during the Cold War?",
    options: ["Berlin", "Madrid", "Rome", "Lisbon"],
    correctAnswer: "Berlin",
    explanation: "The Berlin Wall divided East and West Berlin from 1961 until 1989.",
  },
  {
    id: "h-m-03",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "medium",
    question: "In which year did India become a republic?",
    options: ["1947", "1950", "1952", "1962"],
    correctAnswer: "1950",
    explanation: "India's Constitution came into effect on 26 January 1950.",
  },
  {
    id: "h-m-04",
    topic: "history",
    subtopic: "European History",
    difficulty: "medium",
    question: "Which revolution began in France in 1789?",
    options: [
      "Industrial Revolution",
      "French Revolution",
      "Russian Revolution",
      "Glorious Revolution",
    ],
    correctAnswer: "French Revolution",
    explanation: "The French Revolution began in 1789.",
  },
  {
    id: "h-m-05",
    topic: "history",
    subtopic: "World History",
    difficulty: "medium",
    question: "Who was the first president of the United States?",
    options: [
      "Thomas Jefferson",
      "George Washington",
      "John Adams",
      "Abraham Lincoln",
    ],
    correctAnswer: "George Washington",
    explanation: "George Washington served as the first US president.",
  },
  {
    id: "h-m-06",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "medium",
    question: "Who led the Dandi Salt March in 1930?",
    options: [
      "Subhas Chandra Bose",
      "Mahatma Gandhi",
      "Bhagat Singh",
      "Bal Gangadhar Tilak",
    ],
    correctAnswer: "Mahatma Gandhi",
    explanation: "Gandhi led the Salt March to protest British salt laws.",
  },
  {
    id: "h-m-07",
    topic: "history",
    subtopic: "European History",
    difficulty: "medium",
    question: "The Renaissance began in which European country?",
    options: ["Italy", "Norway", "Ireland", "Poland"],
    correctAnswer: "Italy",
    explanation: "The Renaissance began in Italy before spreading across Europe.",
  },
  {
    id: "h-m-08",
    topic: "history",
    subtopic: "World History",
    difficulty: "medium",
    question: "Which empire was ruled by Suleiman the Magnificent?",
    options: [
      "Ottoman Empire",
      "Mongol Empire",
      "Roman Empire",
      "Mughal Empire",
    ],
    correctAnswer: "Ottoman Empire",
    explanation: "Suleiman ruled the Ottoman Empire during the 16th century.",
  },

  // =====================================================
  // HISTORY — HARD (8)
  // =====================================================
  {
    id: "h-h-01",
    topic: "history",
    subtopic: "Ancient History",
    difficulty: "hard",
    question: "Which writing system was used in ancient Mesopotamia?",
    options: ["Cuneiform", "Hangul", "Latin alphabet", "Morse code"],
    correctAnswer: "Cuneiform",
    explanation: "Cuneiform was a wedge-shaped writing system used in ancient Mesopotamia.",
  },
  {
    id: "h-h-02",
    topic: "history",
    subtopic: "Political History",
    difficulty: "hard",
    question: "The Peace of Westphalia is associated with ending which conflict?",
    options: [
      "Hundred Years' War",
      "Thirty Years' War",
      "Crimean War",
      "Napoleonic Wars",
    ],
    correctAnswer: "Thirty Years' War",
    explanation: "The 1648 treaties helped bring the Thirty Years' War to an end.",
  },
  {
    id: "h-h-03",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "hard",
    question: "Which ancient Indian text on statecraft is traditionally attributed to Kautilya?",
    options: ["Arthashastra", "Rigveda", "Indica", "Silappatikaram"],
    correctAnswer: "Arthashastra",
    explanation: "The Arthashastra is an ancient treatise on statecraft traditionally attributed to Kautilya.",
  },
  {
    id: "h-h-04",
    topic: "history",
    subtopic: "World History",
    difficulty: "hard",
    question: "In which year did the Meiji Restoration begin?",
    options: ["1603", "1750", "1868", "1912"],
    correctAnswer: "1868",
    explanation: "The Meiji Restoration began in 1868 and transformed Japan's political system.",
  },
  {
    id: "h-h-05",
    topic: "history",
    subtopic: "World History",
    difficulty: "hard",
    question: "Which treaty was signed by Germany and the Allied Powers after World War I?",
    options: [
      "Treaty of Versailles",
      "Treaty of Utrecht",
      "Treaty of Tordesillas",
      "Treaty of Ghent",
    ],
    correctAnswer: "Treaty of Versailles",
    explanation: "The Treaty of Versailles was signed in 1919.",
  },
  {
    id: "h-h-06",
    topic: "history",
    subtopic: "Indian History",
    difficulty: "hard",
    question: "Which dynasty built the Brihadeeswarar Temple at Thanjavur?",
    options: ["Chola dynasty", "Gupta dynasty", "Kushan dynasty", "Pala dynasty"],
    correctAnswer: "Chola dynasty",
    explanation: "Rajaraja Chola I commissioned the temple during the Chola period.",
  },
  {
    id: "h-h-07",
    topic: "history",
    subtopic: "Ancient History",
    difficulty: "hard",
    question: "Which Carthaginian general crossed the Alps during the Second Punic War?",
    options: ["Hannibal", "Scipio Africanus", "Julius Caesar", "Xerxes"],
    correctAnswer: "Hannibal",
    explanation: "Hannibal led his army across the Alps during the Second Punic War.",
  },
  {
    id: "h-h-08",
    topic: "history",
    subtopic: "European History",
    difficulty: "hard",
    question: "Which 1957 agreement established the European Economic Community?",
    options: [
      "Treaty of Rome",
      "Treaty of Paris",
      "Maastricht Treaty",
      "Treaty of Lisbon",
    ],
    correctAnswer: "Treaty of Rome",
    explanation: "The Treaty of Rome established the European Economic Community.",
  },

  // =====================================================
  // GEOGRAPHY — EASY (8)
  // =====================================================
  {
    id: "geo-e-01",
    topic: "geography",
    subtopic: "World Geography",
    difficulty: "easy",
    question: "Which is the largest continent by land area?",
    options: ["Africa", "Europe", "Asia", "South America"],
    correctAnswer: "Asia",
    explanation: "Asia is the largest continent by land area.",
  },
  {
    id: "geo-e-02",
    topic: "geography",
    subtopic: "Landforms",
    difficulty: "easy",
    question: "What is the world's highest mountain above sea level?",
    options: ["K2", "Mount Everest", "Kilimanjaro", "Denali"],
    correctAnswer: "Mount Everest",
    explanation: "Mount Everest has the highest summit above sea level.",
  },
  {
    id: "geo-e-03",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "easy",
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctAnswer: "Canberra",
    explanation: "Canberra is Australia's capital.",
  },
  {
    id: "geo-e-04",
    topic: "geography",
    subtopic: "Continents",
    difficulty: "easy",
    question: "Which continent is Brazil located in?",
    options: ["Africa", "South America", "Europe", "Asia"],
    correctAnswer: "South America",
    explanation: "Brazil is the largest country in South America.",
  },
  {
    id: "geo-e-05",
    topic: "geography",
    subtopic: "Oceans",
    difficulty: "easy",
    question: "Which ocean lies between Africa and Australia?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Southern Ocean",
    ],
    correctAnswer: "Indian Ocean",
    explanation: "The Indian Ocean lies between Africa, Asia, Australia and the Southern Ocean.",
  },
  {
    id: "geo-e-06",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "easy",
    question: "Which country is famous for the pyramids at Giza?",
    options: ["Egypt", "India", "Peru", "Greece"],
    correctAnswer: "Egypt",
    explanation: "The Giza pyramid complex is located in Egypt.",
  },
  {
    id: "geo-e-07",
    topic: "geography",
    subtopic: "Landforms",
    difficulty: "easy",
    question: "What is a broad area of relatively flat land called?",
    options: ["Plateau", "Plain", "Valley", "Peninsula"],
    correctAnswer: "Plain",
    explanation: "A plain is a broad area of relatively flat land.",
  },
  {
    id: "geo-e-08",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "easy",
    question: "Which country has a maple leaf on its national flag?",
    options: ["Canada", "Austria", "Denmark", "Japan"],
    correctAnswer: "Canada",
    explanation: "The Canadian flag features a red maple leaf.",
  },

  // =====================================================
  // GEOGRAPHY — MEDIUM (8)
  // =====================================================
  {
    id: "geo-m-01",
    topic: "geography",
    subtopic: "World Geography",
    difficulty: "medium",
    question: "Which river flows through Egypt?",
    options: ["Amazon", "Danube", "Nile", "Mekong"],
    correctAnswer: "Nile",
    explanation: "The Nile flows through northeastern Africa, including Egypt.",
  },
  {
    id: "geo-m-02",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "medium",
    question: "Which country has the city of Marrakech?",
    options: ["Morocco", "Portugal", "Turkey", "Ghana"],
    correctAnswer: "Morocco",
    explanation: "Marrakech is a major city in Morocco.",
  },
  {
    id: "geo-m-03",
    topic: "geography",
    subtopic: "Rivers",
    difficulty: "medium",
    question: "Which river flows through London?",
    options: ["Seine", "Thames", "Tiber", "Rhine"],
    correctAnswer: "Thames",
    explanation: "The River Thames flows through London.",
  },
  {
    id: "geo-m-04",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "medium",
    question: "Which is the largest country in the world by area?",
    options: ["Canada", "China", "Russia", "United States"],
    correctAnswer: "Russia",
    explanation: "Russia is the world's largest country by total area.",
  },
  {
    id: "geo-m-05",
    topic: "geography",
    subtopic: "Climate",
    difficulty: "medium",
    question: "Which line of latitude is at 0 degrees?",
    options: [
      "Tropic of Cancer",
      "Equator",
      "Arctic Circle",
      "Prime Meridian",
    ],
    correctAnswer: "Equator",
    explanation: "The Equator is the line of 0-degree latitude.",
  },
  {
    id: "geo-m-06",
    topic: "geography",
    subtopic: "Mountains",
    difficulty: "medium",
    question: "The Andes mountains are mainly located on which continent?",
    options: ["Europe", "South America", "Africa", "Asia"],
    correctAnswer: "South America",
    explanation: "The Andes extend along the western side of South America.",
  },
  {
    id: "geo-m-07",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "medium",
    question: "What is the capital of South Korea?",
    options: ["Busan", "Seoul", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    explanation: "Seoul is the capital of South Korea.",
  },
  {
    id: "geo-m-08",
    topic: "geography",
    subtopic: "Deserts",
    difficulty: "medium",
    question: "The Sahara Desert is on which continent?",
    options: ["Asia", "Africa", "Australia", "South America"],
    correctAnswer: "Africa",
    explanation: "The Sahara spans much of North Africa.",
  },

  // =====================================================
  // GEOGRAPHY — HARD (8)
  // =====================================================
  {
    id: "geo-h-01",
    topic: "geography",
    subtopic: "Physical Geography",
    difficulty: "hard",
    question: "Which strait separates Europe from Africa?",
    options: [
      "Bering Strait",
      "Strait of Gibraltar",
      "Malacca Strait",
      "Bosporus",
    ],
    correctAnswer: "Strait of Gibraltar",
    explanation: "The Strait of Gibraltar separates southern Spain from northern Morocco.",
  },
  {
    id: "geo-h-02",
    topic: "geography",
    subtopic: "Physical Geography",
    difficulty: "hard",
    question: "Which lake is generally recognized as the world's deepest?",
    options: [
      "Lake Victoria",
      "Lake Superior",
      "Lake Baikal",
      "Lake Tanganyika",
    ],
    correctAnswer: "Lake Baikal",
    explanation: "Lake Baikal in Siberia is the world's deepest lake by maximum depth.",
  },
  {
    id: "geo-h-03",
    topic: "geography",
    subtopic: "Physical Geography",
    difficulty: "hard",
    question: "What is the deepest known ocean trench?",
    options: [
      "Java Trench",
      "Mariana Trench",
      "Tonga Trench",
      "Puerto Rico Trench",
    ],
    correctAnswer: "Mariana Trench",
    explanation: "The Mariana Trench contains the deepest known point in the ocean.",
  },
  {
    id: "geo-h-04",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "hard",
    question: "Which African country was formerly known as Abyssinia?",
    options: ["Ethiopia", "Eritrea", "Somalia", "Sudan"],
    correctAnswer: "Ethiopia",
    explanation: "Abyssinia is a historical name for Ethiopia.",
  },
  {
    id: "geo-h-05",
    topic: "geography",
    subtopic: "Rivers",
    difficulty: "hard",
    question: "Which river has the greatest average discharge of water?",
    options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
    correctAnswer: "Amazon",
    explanation: "The Amazon has the greatest average discharge of any river.",
  },
  {
    id: "geo-h-06",
    topic: "geography",
    subtopic: "Physical Geography",
    difficulty: "hard",
    question: "Which type of plate boundary formed the Himalayas?",
    options: [
      "Divergent boundary",
      "Oceanic transform boundary",
      "Continental collision",
      "Oceanic subduction only",
    ],
    correctAnswer: "Continental collision",
    explanation: "The Himalayas formed through the collision of the Indian and Eurasian plates.",
  },
  {
    id: "geo-h-07",
    topic: "geography",
    subtopic: "Countries",
    difficulty: "hard",
    question: "Which country is completely surrounded by South Africa?",
    options: ["Lesotho", "Botswana", "Namibia", "Zimbabwe"],
    correctAnswer: "Lesotho",
    explanation: "Lesotho is an enclaved country entirely surrounded by South Africa.",
  },
  {
    id: "geo-h-08",
    topic: "geography",
    subtopic: "Climate",
    difficulty: "hard",
    question: "Which warm ocean current helps moderate western Europe's climate?",
    options: [
      "Labrador Current",
      "Gulf Stream and its extension",
      "California Current",
      "Peru Current",
    ],
    correctAnswer: "Gulf Stream and its extension",
    explanation: "The Gulf Stream and North Atlantic Drift transport warm water toward western Europe.",
  },
];